### ISSUE TITLE
Question about compatibility with 'protoc --decode_raw'

### ISSUE THREAD

**Issue by silverwind** [nevermoe/protobuf-decoder#5]
I have a certain protobuf binary file (which I can't post right now because of sensitive data) which fails to parse using `protoc --decode_raw` but to my surprise, this decoder seems to be able to decode it.

Now I'm wondering if I have hit a bug in `protoc` or if this parser is too lenient. Is this expected that both parsers are not fully compatible? If you're interested, I can probably post a sanitized file later for closer investigation.

**Comment by silverwind** [comment]
Found my issue: The file in question had a trailing newline (0x0a) which protoc seems to be strict about:

````bash
$ echo -n "\x08\x96\x01" | protoc --decode_raw
1: 150
$ echo -n "\x08\x96\x01\n" | protoc --decode_raw
Failed to parse input.
````

````bash
$ python protobuf-decoder/parse.py <(echo -n "\x08\x96\x01")
{
    "01:00:Varint": 150
}
$ python protobuf-decoder/parse.py <(echo -n "\x08\x96\x01\n")
{
    "01:00:Varint": 150
}
````
Maybe you want to implement the same strictness if compatibility with `protoc` is a goal.

**Comment by nevermoe** [comment]
thanks!
